-- AlterEnum
ALTER TYPE "MenuStatus" ADD VALUE 'FAILED';

-- AlterTable
ALTER TABLE "Menu" ALTER COLUMN "promptVersion" SET DEFAULT 'v1.0',
ALTER COLUMN "aiModel" DROP NOT NULL,
ALTER COLUMN "tokensIn" DROP NOT NULL,
ALTER COLUMN "tokensOut" DROP NOT NULL,
ALTER COLUMN "costUsd" DROP NOT NULL,
ALTER COLUMN "rawResponse" DROP NOT NULL,
ALTER COLUMN "parsedMenu" DROP NOT NULL,
ALTER COLUMN "shoppingList" DROP NOT NULL;
